### ISSUE TITLE
ModuleNotFoundError: No module named 'blinker._saferef'

### ISSUE THREAD

**Issue by UnKN0WN08** [leoshabit/Auto-Gmail-Creator#61]
hello!
everytime i run this app this appears

```Traceback (most recent call last):
  File "C:\Users\UnKNOWN\Desktop\Auto-Gmail-Creator-master\Auto-Gmail-Creator-master\app.py", line 2, in <module>
    from seleniumwire import webdriver
  File "C:\Users\UnKNOWN\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\seleniumwire\webdriver.py", line 28, in <module>
    from seleniumwire import backend, utils
  File "C:\Users\UnKNOWN\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\seleniumwire\backend.py", line 4, in <module>
    from seleniumwire.server import MitmProxy
  File "C:\Users\UnKNOWN\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\seleniumwire\server.py", line 5, in <module>
    from seleniumwire.handler import InterceptRequestHandler
  File "C:\Users\UnKNOWN\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\seleniumwire\handler.py", line 5, in <module>
    from seleniumwire import har
  File "C:\Users\UnKNOWN\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\seleniumwire\har.py", line 11, in <module>
    from seleniumwire.thirdparty.mitmproxy import connections
  File "C:\Users\UnKNOWN\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\seleniumwire\thirdparty\mitmproxy\connections.py", line 10, in <module>
    from seleniumwire.thirdparty.mitmproxy.net import tls, tcp
  File "C:\Users\UnKNOWN\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\seleniumwire\thirdparty\mitmproxy\net\tls.py", line 15, in <module>
    import seleniumwire.thirdparty.mitmproxy.options
  File "C:\Users\UnKNOWN\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\seleniumwire\thirdparty\mitmproxy\options.py", line 5, in <module>
    from seleniumwire.thirdparty.mitmproxy import optmanager
  File "C:\Users\UnKNOWN\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\seleniumwire\thirdparty\mitmproxy\optmanager.py", line 9, in <module>
    import blinker._saferef
ModuleNotFoundError: No module named 'blinker._saferef' ```

although blinker is installed i also tried is after re installing blinker but it is still showing this

can somebody help pls

**Comment by xoortiN** [comment]
Please, uninstall the version of blinker._saferef, issue the command below:

```
pip uninstall selenium-wire 
pip uninstall blinker
```
once its uninstall use the blinker version which is less than 1.8.0, use following command:

`pip install blinker==1.7.0`

Finally install selenium-wire:

`pip install selenium-wire`

This helped me :)

**Comment by victorAFRodrigues** [comment]
obs: i try with proxy(free) and no proxy.
